project_id = "pnslbftwceqremqsfylk"

[functions.lookup-addresses]
verify_jwt = false

[functions.send-household-form-email]
verify_jwt = false

[functions.send-dbs-request-email]
verify_jwt = false

[functions.send-applicant-dbs-summary]
verify_jwt = false

[functions.send-16th-birthday-alert]
verify_jwt = false

[functions.check-upcoming-birthdays]
verify_jwt = false

[functions.sync-household-members]
verify_jwt = false

[functions.submit-household-form]
verify_jwt = false

[functions.approve-and-convert-to-employee]
verify_jwt = false

[functions.check-all-16th-birthdays]
verify_jwt = false
