project_id = "pnslbftwceqremqsfylk"

[functions.lookup-addresses]
verify_jwt = false

[functions.send-household-form-email]
verify_jwt = false

[functions.send-dbs-request-email]
verify_jwt = false

[functions.send-applicant-dbs-summary]
verify_jwt = false

[functions.send-employee-dbs-summary]
verify_jwt = false

[functions.send-16th-birthday-alert]
verify_jwt = false

[functions.check-upcoming-birthdays]
verify_jwt = false

[functions.sync-household-members]
verify_jwt = false

[functions.submit-household-form]
verify_jwt = false

[functions.approve-and-convert-to-employee]
verify_jwt = false

[functions.check-all-16th-birthdays]
verify_jwt = false

[functions.sync-assistants]
verify_jwt = false

[functions.send-assistant-form-email]
verify_jwt = false

[functions.submit-assistant-form]
verify_jwt = false

[functions.send-reference-request-email]
verify_jwt = false

[functions.submit-reference-form]
verify_jwt = false

[functions.send-known-to-ofsted-email]
verify_jwt = false

[functions.send-la-check-email]
verify_jwt = false

[functions.send-cochildminder-form-email]
verify_jwt = false

[functions.submit-cochildminder-form]
verify_jwt = false

[functions.check-compliance-status]
verify_jwt = false

[functions.delete-employee-reset-application]
verify_jwt = false